53 fix coding style and cmake incorporation
francoisbaudouin/r-types pull request #64
Opened 2023-10-17 16:14 UTC by francoisbaudouin

2023-10-17 17:51 UTC, Rafouzou submitted a review, later dismissed
Multiple files don't end with a newline character, is this ok?

2023-10-18 08:58 UTC, Rafouzou approved these changes

2023-10-18 09:08 UTC, ThibaultGuyony requested changes
Juste change the comment and it's good. 
You can also remove the fonction in system.hpp

2023-10-18 09:08 UTC, ThibaultGuyony commented on src/ECS/logging_system.cpp
File useless

2023-10-18 09:21 UTC, merged