66 refactor sfml into raylib
francoisbaudouin/r-types pull request #76
Opened 2023-10-24 22:02 UTC by Rafouzou

- All the display now runs on Raylib
- There is music
- There is a 'settings' page to change the volume of the music
- The game displays the player and one enemy with a parallax behind
- Some new assets were added

2023-10-25 11:45 UTC, francoisbaudouin requested changes
See comment.

Be aware, don't duplicate code and respect the existent packet manager.
If you have question of packet manager ask me.

Also, pls lint the code. To do that follow the next instruction:

under fedora:

sudo dnf install clang-tools-extra

ubuntu:

sudo apt install clang-format

In vs code, install extension Clang-Format by publisher:"Xaver Hellauer"

2023-10-25 11:45 UTC, francoisbaudouin commented on src/client/CMakeLists.txt
> +
remove fetchContent, it's NOT matched in our packages architecture 

add:

find_package(raylib REQUIRED COMPONENTS graphics window system audio)

2023-10-25 11:45 UTC, francoisbaudouin commented on src/client/CMakeLists.txt
> +# target_link_libraries(${TARGET_NAME} PUBLIC sfml::sfml)
Remove comment. Sfml is not needed anymore

2023-10-25 11:45 UTC, francoisbaudouin commented on src/client/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} PRIVATE Threads::Threads pthread dl)
Remove this line, is duplicate from line 58

2023-10-25 11:45 UTC, francoisbaudouin commented on src/client/CMakeLists.txt
>  target_link_libraries(${TARGET_NAME} PUBLIC boost::boost)
remove the line and move boost::boost to the line 66

the line become
target_link_libraries(${TARGET_NAME} PRIVATE Boost::filesystem Boost::system Boost::serialization, boost::boost)

2023-10-27 18:21 UTC, ThibaultGuyony approved these changes
LGTM

2023-10-27 23:03 UTC, francoisbaudouin approved these changes
ok

2023-10-28 07:01 UTC, merged